'use strict';
// Same-origin Deriv OAuth2 (code + PKCE) backend-for-frontend for Apex Sentinel.
const L = require('../lib/deriv-session');
const RETURN_PATH = /^\/(?!\/)[^\r\n]*$/;
const ACCOUNT_ID = /^[A-Z0-9]{3,32}$/;
const routeOf = event => { let p=event.path||''; try{if(event.rawUrl)p=new URL(event.rawUrl).pathname;}catch{} const m=p.match(/(oauth-start|oauth-callback|trader-session|trader-accounts|trader-otp)\/?$/); return m?m[1]:null; };
const errStatus=(e,d)=>Number(e&&e.status)||d;
const errCode=(e,d)=>String((e&&e.code)||d);
const oauthStart=async(event,id)=>{if(event.httpMethod!=='POST')return L.fail(405,'method_not_allowed','Method not allowed',id);const cfg=L.env();if(!cfg.clientId||!cfg.appId||!cfg.origin)return L.fail(500,'server_misconfigured','Deriv application configuration is incomplete',id);if(!L.siteOk(event))return L.fail(400,'site_mismatch','Site identifier is invalid',id);if(!L.originOk(event,true))return L.fail(403,'origin_denied','Origin is not allowed',id);let body;try{body=JSON.parse(event.body||'{}')}catch{return L.fail(400,'invalid_body','Invalid request body',id)}const scopes=Array.isArray(body.scopes)?[...new Set(body.scopes.map(String))]:[];if(!scopes.length||scopes.some(s=>!L.KNOWN_SCOPES.includes(s)))return L.fail(400,'invalid_scope','At least one supported scope is required',id);if(scopes.some(s=>!cfg.allowedScopes.includes(s)))return L.fail(409,'scope_not_configured','A requested feature needs a scope not configured for this application',id);const returnPath=typeof body.returnPath==='string'&&RETURN_PATH.test(body.returnPath)?body.returnPath:'/';const state=L.randomSecret(32),verifier=L.randomSecret(64),expires=Date.now()+600000;const txCookie=L.cookie(L.TX_COOKIE,L.seal({state,verifier,returnPath,scopes,exp:expires}),600);const url=new URL(L.DERIV_AUTHORIZATION_URL);url.searchParams.set('response_type','code');url.searchParams.set('client_id',cfg.clientId);url.searchParams.set('redirect_uri',cfg.redirectUri||`${cfg.origin}/api/deriv-oauth-callback`);url.searchParams.set('scope',scopes.join(' '));url.searchParams.set('state',state);url.searchParams.set('code_challenge',L.sha256(verifier));url.searchParams.set('code_challenge_method','S256');return L.respond(200,{authorizationUrl:url.toString(),expiresAt:new Date(expires).toISOString(),correlationId:id},[txCookie]);};
const oauthCallback=async(event,id)=>{if(event.httpMethod!=='GET')return L.fail(405,'method_not_allowed','Method not allowed',id);const cfg=L.env(),q=event.queryStringParameters||{},tx=L.unseal(L.readCookie(event,L.TX_COOKIE)),clear=L.clearCookie(L.TX_COOKIE);if(!tx||tx.exp<Date.now()||!q.state||!L.safeEqual(q.state,tx.state))return L.fail(400,'state_invalid','OAuth state is invalid, expired, or already used',id,[clear]);const back=code=>{const t=new URL(tx.returnPath,cfg.origin);t.searchParams.set('auth_error',code);t.searchParams.set('correlation_id',id);return L.redirect(t.toString(),[clear]);};if(q.error||!q.code)return back(q.error?'login_cancelled':'code_missing');try{const t=await L.tokenRequest({grant_type:'authorization_code',code:q.code,client_id:cfg.clientId,redirect_uri:cfg.redirectUri||`${cfg.origin}/api/deriv-oauth-callback`,code_verifier:tx.verifier});if(!t.access_token)throw new Error('missing access token');const granted=t.scope?t.scope.split(/\s+/).filter(Boolean):tx.scopes;if(tx.scopes.some(s=>!granted.includes(s)))return back('required_scope_missing');const sessionSeconds=t.refresh_token?604800:Math.max(60,t.expires_in||3600);const session={at:t.access_token,rt:t.refresh_token||null,accessExp:new Date(Date.now()+(t.expires_in||3600)*1000).toISOString(),sessionExp:new Date(Date.now()+sessionSeconds*1000).toISOString(),scopes:granted,csrf:L.randomSecret(32)};const target=new URL(tx.returnPath,cfg.origin);target.searchParams.set('auth','connected');return L.redirect(target.toString(),[L.cookie(L.SESSION_COOKIE,L.seal(session),sessionSeconds),clear]);}catch(e){console.error('deriv-oauth-callback failed',{correlationId:id,code:errCode(e,'token_exchange_failed')});return back('token_exchange_failed');}};
const session=async(event,id)=>{if(event.httpMethod==='GET'){const{s,refreshedCookie}=await L.loadSession(event);return L.respond(200,{authenticated:true,siteId:L.env().siteId,scopes:s.scopes,expiresAt:s.sessionExp,csrfToken:s.csrf,correlationId:id},refreshedCookie?[refreshedCookie]:[]);}if(event.httpMethod==='DELETE'){await L.loadSession(event,{csrf:true});return L.respond(200,{authenticated:false,correlationId:id},[L.clearCookie(L.SESSION_COOKIE)]);}return L.fail(405,'method_not_allowed','Method not allowed',id);};
const accounts=async(event,id)=>{if(event.httpMethod!=='GET')return L.fail(405,'method_not_allowed','Method not allowed',id);const{s,refreshedCookie}=await L.loadSession(event);if(!s.scopes.includes('trade'))return L.fail(403,'scope_missing','Reconnect with trade permission to view Options accounts',id);const result=await L.derivRequest('/trading/v1/options/accounts',{accessToken:s.at});const data=(Array.isArray(result.data)?result.data:[]).map(a=>({account_id:String(a.account_id||''),account_type:a.account_type==='real'?'real':'demo',balance:typeof a.balance==='number'||typeof a.balance==='string'?a.balance:0,currency:typeof a.currency==='string'?a.currency:'',group:typeof a.group==='string'?a.group:'',status:typeof a.status==='string'?a.status:''})).filter(a=>a.account_id);return L.respond(200,{data,correlationId:id},refreshedCookie?[refreshedCookie]:[]);};
const otp=async(event,id)=>{if(event.httpMethod!=='POST')return L.fail(405,'method_not_allowed','Method not allowed',id);const{s,refreshedCookie}=await L.loadSession(event,{csrf:true});if(!s.scopes.includes('trade'))return L.fail(403,'scope_missing','Reconnect with trade permission to trade',id);let body;try{body=JSON.parse(event.body||'{}')}catch{return L.fail(400,'invalid_body','Invalid request body',id)}const accountId=String(body.accountId||'').toUpperCase();if(!ACCOUNT_ID.test(accountId))return L.fail(400,'account_invalid','Account identifier is invalid',id);const list=await L.derivRequest('/trading/v1/options/accounts',{accessToken:s.at});if(!(list.data||[]).some(a=>a.account_id===accountId))return L.fail(403,'account_denied','This account is not available in the current Deriv session',id);const result=await L.derivRequest(`/trading/v1/options/accounts/${encodeURIComponent(accountId)}/otp`,{accessToken:s.at,method:'POST'});const ws=new URL(result.data.url);if(ws.protocol!=='wss:'||ws.hostname!=='api.derivws.com')throw Object.assign(new Error('Deriv returned an invalid WebSocket endpoint'),{code:'otp_endpoint_invalid',status:502});return L.respond(200,{data:{url:ws.toString()},correlationId:id},refreshedCookie?[refreshedCookie]:[]);};
const handlers={'oauth-start':oauthStart,'oauth-callback':oauthCallback,'trader-session':session,'trader-accounts':accounts,'trader-otp':otp};
exports.handler=async event=>{const id=require('crypto').randomUUID(),route=routeOf(event);if(!route)return L.fail(404,'not_found','Unknown endpoint',id);try{return await handlers[route](event,id)}catch(e){const status=errStatus(e,route==='trader-session'?401:502),code=errCode(e,'request_failed');if(status>=500)console.error(`deriv-auth ${route} failed`,{correlationId:id,code,status});const msg=status===401?'Deriv session expired; reconnect your account':status>=500?'Request could not be completed':e.message;return L.fail(status,code,msg,id,status===401?[L.clearCookie(L.SESSION_COOKIE)]:[]);}};