import {useState} from "react";
import {useSentinelForge} from "@/hooks/useSentinelForge";
import {CONNECTION_STATUS} from "@/external/bot-skeleton/services/api/observables/connection-status-stream";
import "./sentinel-forge.scss";
function fmtTime(ts:number){const d=new Date(ts);return d.toLocaleTimeString(undefined,{hour12:false})}
export default function SentinelForge(){
 const {apex,api,executor,risk,session,queue,openContracts,journal,executeManual,updateRisk}=useSentinelForge();
 const [stake,setStake]=useState(risk.baseStake);
 const signal=executor.getStagedSignal();
 const connected=api.isAuthorized&&api.connectionStatus===CONNECTION_STATUS.OPENED;
 const executing=executor.isExecuting();
 const inRecovery=risk.martingaleEnabled&&(session.recoveryTotalLost>0||session.currentRecoveryStep>0);
 return <div className="sentinel-forge">
  <div className="forge-head"><div><div className="forge-kicker">SENTINEL FORGE</div><h1>Signal execution workspace</h1><p>Sentinel intelligence remains authoritative. Forge only controls execution.</p></div><div className="forge-health"><span className={connected?"dot live":"dot"}></span>{connected?"ACCOUNT CONNECTED":"ACCOUNT OFFLINE"}<b>{api.activeLoginid||"—"}</b></div></div>
  <div className="forge-grid">
   <section className="forge-card signal"><div className="card-title">CURRENT SENTINEL SIGNAL</div>{signal ? <><div className="signal-main">{signal.contractLabel}<span>{signal.market}</span></div><div className="metrics"><div><small>ENTRY DIGIT</small><b>{signal.entryDigit??"—"}</b></div><div><small>STATUS</small><b>{signal.sentinelStatus}</b></div><div><small>SCORE</small><b>{signal.score}</b></div><div><small>NEXT STAKE</small><b>{executor.getEffectiveNextStake().toFixed(2)}</b></div></div>{inRecovery && <div className="recovery-banner">RECOVERING · step {session.currentRecoveryStep} · total lost ${session.recoveryTotalLost.toFixed(2)}</div>}<button className="forge-primary" disabled={executing||!connected||(executor.getMode()==="LIVE"&&executor.getStatus()==="ACCOUNT_DISCONNECTED")} onClick={()=>executeManual(signal)}>{executing?"EXECUTING…":"EXECUTE SIGNAL"}</button></> : <div className="empty">Waiting for a surfaced Sentinel signal…<br/><span>{apex.status.toUpperCase()} · {apex.online}/{apex.total} markets live</span>{session.pendingRecovery && <div className="recovery-banner">Holding recovery for next {session.pendingRecovery.direction} signal · digit {session.pendingRecovery.digit} · stake ${session.pendingRecovery.stake.toFixed(2)}</div>}</div>}</section>
   <section className="forge-card">
    <div className="card-title">EXECUTION</div>
    <label>MODE<select value={executor.getMode()} onChange={e=>executor.setMode(e.target.value as any)}><option value="PAPER">PAPER</option><option value="LIVE">LIVE</option></select></label>
    <label>BASE STAKE<input type="number" min=".35" step=".01" value={stake} onChange={e=>{const v=Number(e.target.value);setStake(v);updateRisk({baseStake:v,stake:v})}}/></label>
    <label>ENTRY MODE<select value={risk.entryMode} onChange={e=>updateRisk({entryMode:e.target.value as any})}><option value="WAIT_FOR_ENTRY_DIGIT">Wait for entry digit</option><option value="INSTANT">Execute instantly</option></select></label>
    <div className="field-pair"><label>OVER default entry<input type="number" min="0" max="9" value={risk.defaultEntryDigitOver} onChange={e=>updateRisk({defaultEntryDigitOver:Number(e.target.value)})}/></label><label>UNDER default entry<input type="number" min="0" max="9" value={risk.defaultEntryDigitUnder} onChange={e=>updateRisk({defaultEntryDigitUnder:Number(e.target.value)})}/></label></div>
    <label>RUN MODE<select value={risk.runMode} onChange={e=>updateRisk({runMode:e.target.value as any})}><option value="PER_SIGNAL">One run per signal</option><option value="CONTINUOUS">Continuous — run until stopped</option></select></label>
    {risk.runMode==="PER_SIGNAL" && <label>RECOVERY TIMING<select value={risk.recoveryTiming} onChange={e=>updateRisk({recoveryTiming:e.target.value as any})}><option value="INSTANT">Instant — recover right after the loss</option><option value="NEXT_SIGNAL">Wait for the next signal</option></select></label>}
    <div className="toggle-row"><span>MARTINGALE RECOVERY</span><button className={risk.martingaleEnabled?"toggle on":"toggle"} onClick={()=>updateRisk({martingaleEnabled:!risk.martingaleEnabled})}>{risk.martingaleEnabled?"ON":"OFF"}</button></div>
    {risk.martingaleEnabled && <><label>MARTINGALE TYPE<select value={risk.martingaleMode} onChange={e=>updateRisk({martingaleMode:e.target.value as any})}><option value="SPLIT">Split martingale</option><option value="EXPONENTIAL">Exponential (base × multiplier)</option></select></label>{risk.martingaleMode==="SPLIT" ? <div className="field-pair"><label>SPLIT FACTOR<input type="number" min="1" step="1" value={risk.martingaleSplit} onChange={e=>updateRisk({martingaleSplit:Number(e.target.value)})}/></label><label>PAYOUT %<input type="number" min="1" max="99" value={risk.payoutPercent} onChange={e=>updateRisk({payoutPercent:Number(e.target.value)})}/></label></div> : <label>MULTIPLIER<input type="number" min="1" step=".1" value={risk.martingaleMultiplier} onChange={e=>updateRisk({martingaleMultiplier:Number(e.target.value)})}/></label>}<div className="field-pair"><label>OVER recovery digit<input type="number" min="0" max="9" value={risk.recoveryDigitOver} onChange={e=>updateRisk({recoveryDigitOver:Number(e.target.value)})}/></label><label>UNDER recovery digit<input type="number" min="0" max="9" value={risk.recoveryDigitUnder} onChange={e=>updateRisk({recoveryDigitUnder:Number(e.target.value)})}/></label></div><label>MAX RECOVERY STAKE<input type="number" min=".35" step=".5" value={risk.maxRecoveryStake} onChange={e=>updateRisk({maxRecoveryStake:Number(e.target.value)})}/></label></>}
    <div className="toggle-row"><span>AUTO EXECUTION</span><button className={executor.isAutoArmed()?"toggle on":"toggle"} onClick={()=>executor.setAutoState(executor.isAutoArmed()?"OFF":"ON")}>{executor.isAutoArmed()?"ON":"OFF"}</button></div>
    <button className="danger" onClick={()=>executor.stopAutoTrading()}>STOP</button>
   </section>
   <section className="forge-card"><div className="card-title">ACCOUNT / RISK</div><div className="account-big">{api.authData?.balance??"—"} <span>{api.authData?.currency??""}</span></div><div className="risk-line"><span>Session baseline</span><b>{session.accountStartBalance??"—"}</b></div><div className="risk-line"><span>Account P&amp;L</span><b>{session.accountPnl>=0?"+":""}{session.accountPnl.toFixed(2)}</b></div><label>TARGET PROFIT<input type="number" min="0" step=".5" value={risk.targetProfit??""} placeholder="OFF" onChange={e=>updateRisk({targetProfit:e.target.value===""?null:Number(e.target.value)})}/></label><label>STOP LOSS<input type="number" min="0" step=".5" value={risk.stopLoss??""} placeholder="OFF" onChange={e=>updateRisk({stopLoss:e.target.value===""?null:Number(e.target.value)})}/></label><div className="risk-line"><span>Trades</span><b>{session.tradesCount}/{risk.maxTradesPerSession}</b></div><div className="risk-line"><span>Win rate</span><b>{session.winRate.toFixed(0)}%</b></div><button className="secondary" onClick={()=>executor.resetSessionMetrics()}>RESET SESSION BASELINE</button></section>
   <section className="forge-card wide"><div className="card-title">LIVE EXECUTION</div><div className="execution-state"><b>{executor.getStatus()}</b><span>{executor.getPipelineStep()}</span><span>Open contracts: {openContracts.length}</span></div><div className="queue">{queue.slice(0,6).map(q=><div key={q.signal.id}><span>{q.signal.contractLabel}</span><span>{q.signal.market}</span><b>{q.state}</b></div>)}</div></section>
   <section className="forge-card wide"><div className="card-title">TRANSACTIONS</div>{journal.length===0 ? <div className="empty">No trades yet this session.</div> : <div className="txn-table"><div className="txn-row txn-head"><span>Time</span><span>Market</span><span>Contract</span><span>Stake</span><span>Result</span><span>P/L</span></div>{journal.slice(0,60).map(r=><div key={r.id} className={"txn-row"+(r.result==="WIN"?" is-win":r.result==="LOSS"?" is-loss":r.status==="REJECTED"?" is-rejected":"")}><span>{fmtTime(r.timestamp)}</span><span>{r.market}</span><span>{r.contract} {r.barrier}</span><span>{r.stake!=null?r.stake.toFixed(2):"—"}</span><span>{r.status==="REJECTED"?"REJECTED":r.result||"OPEN"}</span><span>{r.pnl!=null?(r.pnl>=0?"+":"")+r.pnl.toFixed(2):"—"}</span></div>)}</div>}</section>
  </div>
 </div>
}