import {useSentinelForge} from "@/hooks/useSentinelForge";
import {useState} from "react";
import "./sentinel-forge.scss";
export default function SentinelForge(){
 const {apex,api,executor,risk,session,queue,openContracts,executeManual,updateRisk}=useSentinelForge();
 const [stake,setStake]=useState(risk.baseStake); const signal=executor.getStagedSignal();
 const connected=api.isAuthorized&&api.connectionStatus==="OPENED";
 return <div className="sentinel-forge">
  <div className="forge-head"><div><div className="forge-kicker">SENTINEL FORGE</div><h1>Signal execution workspace</h1><p>Sentinel intelligence remains authoritative. Forge only controls execution.</p></div><div className="forge-health"><span className={connected?"dot live":"dot"}></span>{connected?"ACCOUNT CONNECTED":"ACCOUNT OFFLINE"}<b>{api.activeLoginid||"—"}</b></div></div>
  <div className="forge-grid">
   <section className="forge-card signal"><div className="card-title">CURRENT SENTINEL SIGNAL</div>{signal?<><div className="signal-main">{signal.contractLabel}<span>{signal.market}</span></div><div className="metrics"><div><small>ENTRY</small><b>{signal.entryDigit??"—"}</b></div><div><small>STATUS</small><b>{signal.sentinelStatus}</b></div><div><small>SCORE</small><b>{signal.score}</b></div><div><small>RUNS</small><b>{signal.metadata?.runsTotal??1}</b></div></div><button className="forge-primary" disabled={!connected||executor.getMode()==="LIVE"&&executor.getStatus()==="ACCOUNT_DISCONNECTED"} onClick={()=>executeManual(signal)}>EXECUTE SIGNAL</button></>:<div className="empty">Waiting for a surfaced Sentinel signal…<br/><span>{apex.status.toUpperCase()} · {apex.online}/{apex.total} markets live</span></div>}</section>
   <section className="forge-card"><div className="card-title">EXECUTION</div><label>MODE<select value={executor.getMode()} onChange={e=>executor.setMode(e.target.value as any)}><option value="PAPER">PAPER</option><option value="LIVE">LIVE</option></select></label><label>BASE STAKE<input type="number" min=".35" step=".01" value={stake} onChange={e=>{const v=Number(e.target.value);setStake(v);updateRisk({baseStake:v,stake:v})}}/></label><label>RUNS / SIGNAL<input type="number" min="1" max="10" value={(risk as any).runsPerSignal??1} onChange={e=>updateRisk({runsPerSignal:Number(e.target.value)} as any)}/></label><label>RECOVERY DIGIT<input type="number" min="0" max="9" value={(risk as any).recoveryDigit??8} onChange={e=>updateRisk({recoveryDigit:Number(e.target.value)} as any)}/></label><div className="toggle-row"><span>AUTO EXECUTION</span><button className={executor.isAutoArmed()?"toggle on":"toggle"} onClick={()=>executor.setAutoState(executor.isAutoArmed()?"OFF":"ON")}>{executor.isAutoArmed()?"ON":"OFF"}</button></div><button className="danger" onClick={()=>executor.stopAutoTrading()}>EMERGENCY STOP</button></section>
   <section className="forge-card"><div className="card-title">ACCOUNT / RISK</div><div className="account-big">{api.authData?.balance??"—"} <span>{api.authData?.currency??""}</span></div><div className="risk-line"><span>Session baseline</span><b>{session.accountStartBalance??"—"}</b></div><div className="risk-line"><span>Account P&amp;L</span><b>{session.accountPnl>=0?"+":""}{session.accountPnl.toFixed(2)}</b></div><div className="risk-line"><span>Target / Stop</span><b>+{risk.targetProfit??"OFF"} / -{risk.stopLoss??"OFF"}</b></div><div className="risk-line"><span>Trades</span><b>{session.tradesCount}/{risk.maxTradesPerSession}</b></div><button className="secondary" onClick={()=>executor.resetSessionMetrics()}>RESET SESSION BASELINE</button></section>
   <section className="forge-card wide"><div className="card-title">LIVE EXECUTION</div><div className="execution-state"><b>{executor.getStatus()}</b><span>{executor.getPipelineStep()}</span><span>Open contracts: {openContracts.length}</span></div><div className="queue">{queue.slice(0,6).map(q=><div key={q.signal.id}><span>{q.signal.contractLabel}</span><span>{q.signal.market}</span><b>{q.state}</b></div>)}</div></section>
  </div>
 </div>
}