import { api_base } from "@/external/bot-skeleton";
import { derivBus } from "@/lib/deriv/tick-bus";
import { riskManager } from "./risk-manager";
import { executionJournal } from "./execution-journal";
import { calculateStake } from "./stake-calculator";
import { validateSignalStructure } from "./signal-adapter";
import type { ExecutionMode,ExecutionTrigger,ExecutorStatus,ExecutionSignal,RiskSettings,OpenContract,SignalQueueItem,SignalQueueState,AutoExecutionState,SessionState,GateEvaluationResult } from "./types";
import { DEFAULT_RISK_SETTINGS } from "./types";

export interface AccountSession { loginid:string; currency:string; balance:number; isVirtual:boolean; connected:boolean; }
const SETTINGS_KEY="sentinel.forge.settings.v1"; const MAX_QUEUE=50;

class SentinelForgeExecutor {
 private mode:ExecutionMode="PAPER"; private autoState:AutoExecutionState="OFF"; private risk:RiskSettings={...DEFAULT_RISK_SETTINGS};
 private account:AccountSession|null=null; private queue:SignalQueueItem[]=[]; private staged:ExecutionSignal|null=null;
 private open=new Map<string,OpenContract>(); private listeners=new Set<()=>void>(); private lastTickAt=0; private latestError:string|null=null; private pipelineStep="IDLE";
 private baseline:number|null=null; private tradesThisHour:number[]=[]; private executedIds=new Set<string>();
 private session:SessionState={startingBalance:null,accountStartBalance:null,currentAccountBalance:null,accountPnl:0,sessionProfit:0,sessionLoss:0,netPnl:0,tradesCount:0,wins:0,losses:0,winRate:0,consecutiveLosses:0,currentRecoveryStep:0,currentCalculatedStake:.35,isTargetProfitReached:false,isStopLossReached:false,isMaxConsecutiveLossesReached:false,cooldownUntil:0,autoState:"OFF"};
 constructor(){this.load(); derivBus.onTick((s,t)=>{this.lastTickAt=t.t;});}
 private load(){if(typeof window==="undefined")return;try{const x=localStorage.getItem(SETTINGS_KEY);if(x)this.risk={...DEFAULT_RISK_SETTINGS,...JSON.parse(x)}}catch{}}
 private save(){try{localStorage.setItem(SETTINGS_KEY,JSON.stringify(this.risk))}catch{}}
 subscribe(f:()=>void){this.listeners.add(f);return()=>this.listeners.delete(f)} private notify(){this.listeners.forEach(f=>f())}
 getMode(){return this.mode} setMode(m:ExecutionMode){this.mode=m;this.notify()} getAutoState(){return this.autoState} isAutoArmed(){return this.autoState==="ON"}
 setAutoState(s:AutoExecutionState,reason?:string){this.autoState=s;this.session.autoState=s;this.session.pauseReason=reason;if(s==="ON")void this.processQueue();this.notify()}
 pauseAuto(r="Manual pause"){this.setAutoState("PAUSED",r)} resumeAuto(){this.setAutoState("ON")} stopAutoTrading(){this.setAutoState("OFF","Emergency stop");executionJournal.logEvent({type:"EMERGENCY_STOP",signalId:"SYS",message:"Emergency stop: new auto executions disabled."})}
 getRiskSettings(){return {...this.risk}} updateRiskSettings(u:Partial<RiskSettings>){this.risk={...this.risk,...u};this.save();this.notify()}
 setAccount(a:AccountSession|null){this.account=a;if(a){if(this.baseline===null){this.baseline=a.balance;this.session.startingBalance=a.balance;this.session.accountStartBalance=a.balance}this.session.currentAccountBalance=a.balance;this.session.accountPnl=Number((a.balance-(this.baseline??a.balance)).toFixed(2));}else{this.baseline=null;this.session.currentAccountBalance=null;this.session.accountPnl=0}this.notify()}
 resetSessionMetrics(){if(this.account)this.baseline=this.account.balance;this.session={...this.session,startingBalance:this.baseline,accountStartBalance:this.baseline,currentAccountBalance:this.account?.balance??null,accountPnl:0,sessionProfit:0,sessionLoss:0,netPnl:0,tradesCount:0,wins:0,losses:0,winRate:0,consecutiveLosses:0,currentRecoveryStep:0,currentCalculatedStake:this.risk.baseStake,isTargetProfitReached:false,isStopLossReached:false,isMaxConsecutiveLossesReached:false,cooldownUntil:0};this.executedIds.clear();this.notify()}
 getSessionState(){return {...this.session}} getAccount(){return this.account}
 getSignalQueue(){return [...this.queue]} getStagedSignal(){return this.staged} stageSignal(s:ExecutionSignal|null){this.staged=s; if(s){const q=this.queue.find(x=>x.signal.id===s.id);if(q&&q.state==="RECEIVED")q.state="LOADED";executionJournal.logEvent({type:"SIGNAL_LOADED",signalId:s.id,message:"Signal loaded into Forge."})}this.notify()}
 getOpenContracts(){return [...this.open.values()]} getPipelineStep(){return this.pipelineStep} getLatestError(){return this.latestError}
 getEffectiveNextStake(){const r=calculateStake({baseStake:this.risk.baseStake,martingaleEnabled:this.risk.martingaleEnabled,martingaleMultiplier:this.risk.martingaleMultiplier,recoveryStep:this.session.currentRecoveryStep,maxStake:this.risk.maxStake,maxRecoveryStake:this.risk.maxRecoveryStake,accountBalance:this.mode==="LIVE"?this.account?.balance:10000});this.session.currentCalculatedStake=r.stake;return r.stake}
 getStatus():ExecutorStatus{if(this.mode==="LIVE"&&!this.account?.connected)return"ACCOUNT_DISCONNECTED";if(this.pipelineStep==="PROPOSAL"||this.pipelineStep==="BUYING")return"EXECUTING";if(this.autoState==="PAUSED")return"PAUSED";if(this.autoState==="ON")return"ARMED";if(this.lastTickAt&&Date.now()-this.lastTickAt>7000)return"FEED_STALE";return"AUTO_OFF"}
 receiveSignal(signal:ExecutionSignal){const v=validateSignalStructure(signal);if(!v.valid){this.latestError=v.reason||"Invalid signal";return null}if(this.risk.duplicateProtection&&this.queue.some(q=>q.signal.id===signal.id))return this.queue.find(q=>q.signal.id===signal.id)!;const item:SignalQueueItem={signal,state:"RECEIVED",receivedAt:Date.now()};this.queue=[item,...this.queue].slice(0,MAX_QUEUE);executionJournal.logEvent({type:"SIGNAL_RECEIVED",signalId:signal.id,message:"Sentinel signal received by Forge.",details:{sentinelStatus:signal.sentinelStatus}});this.notify();if(this.autoState==="ON"&&this.risk.autoSignalPolicy==="EXECUTE_ALL")void this.awaitEntry(item);return item}
 private async awaitEntry(item:SignalQueueItem){const s=item.signal;if(Date.now()>s.expiresAt){item.state="EXPIRED";return}const digit=s.entryDigit;if(digit===undefined){void this.executeSignal(s,"AUTO");return}item.state="WAITING";this.notify();const market=s.market;const unsub=derivBus.onTick((sym,t)=>{if(sym!==market)return;const pip=derivBus.getPipSize(sym);const d=Math.abs(Math.round(t.price*Math.pow(10,pip)))%10;if(d!==digit)return;unsub();if(Date.now()>s.expiresAt){item.state="EXPIRED";this.notify();return}void this.executeSignal(s,"AUTO")});setTimeout(()=>{unsub();if(item.state==="WAITING"){item.state="EXPIRED";this.notify()}},Math.max(1000,s.expiresAt-Date.now()))}
 private async processQueue(){for(const q of this.queue.filter(x=>x.state==="RECEIVED"||x.state==="LOADED"))await this.awaitEntry(q)}
 private gates(s:ExecutionSignal,trigger:ExecutionTrigger,stake:number):GateEvaluationResult{const age=Date.now()-s.createdAt;if(age>Math.max(30,this.risk.maxSignalAgeSeconds)*1000)return{ok:false,reason:"Signal expired"};if(trigger==="AUTO"&&this.autoState!=="ON")return{ok:false,reason:"Auto execution is OFF"};if(trigger==="AUTO"&&this.risk.autoSignalPolicy==="SELECTED_TYPES"&&!this.risk.allowedContractTypes.includes(s.contractType))return{ok:false,reason:"Contract type excluded by execution policy"};if(this.mode==="LIVE"&&(!this.account?.connected||!this.account.loginid))return{ok:false,reason:"Account disconnected"};if(this.mode==="LIVE"&&(this.account?.balance??0)<stake)return{ok:false,reason:"Insufficient account balance"};if(this.open.size>=this.risk.maxOpenContracts)return{ok:false,reason:"Maximum open contracts reached"};if(this.risk.targetProfit!==null&&this.session.accountPnl>=this.risk.targetProfit)return{ok:false,reason:"Target profit reached"};if(this.risk.stopLoss!==null&&this.session.accountPnl<=-this.risk.stopLoss)return{ok:false,reason:"Stop loss reached"};if(this.risk.maxConsecutiveLosses!==null&&this.session.consecutiveLosses>=this.risk.maxConsecutiveLosses)return{ok:false,reason:"Maximum consecutive losses reached"};if(this.risk.maxTradesPerSession!==null&&this.session.tradesCount>=this.risk.maxTradesPerSession)return{ok:false,reason:"Session trade limit reached"};if(stake<.35||stake>this.risk.maxStake)return{ok:false,reason:"Stake outside configured bounds"};return{ok:true}}
 async executeSignal(s:ExecutionSignal,trigger:ExecutionTrigger="MANUAL",customStake?:number){const stake=customStake??this.getEffectiveNextStake();if(this.executedIds.has(s.id)&&this.risk.duplicateProtection)return{ok:false,error:"Duplicate signal"};const gate=this.gates(s,trigger,stake);if(!gate.ok){executionJournal.recordRejection({signalId:s.id,account:this.account?.loginid??"N/A",market:s.market,contract:s.contractType,barrier:s.barrier,duration:s.duration,stake,confidence:s.confidence,confluence:s.confluence,reason:gate.reason||"Execution blocked",mode:this.mode+"_"+trigger as any});return{ok:false,error:gate.reason};}this.executedIds.add(s.id);this.pipelineStep="PROPOSAL";this.notify();if(this.mode==="PAPER"){await new Promise(r=>setTimeout(r,50));this.session.tradesCount++;this.session.netPnl+=0;this.pipelineStep="IDLE";this.notify();return{ok:true,contractId:"PAPER-"+Date.now()}}try{if(!api_base.api)throw new Error("Deriv connection unavailable");const proposal:any=await api_base.api.send({proposal:1,amount:stake,basis:"stake",contract_type:s.contractType,currency:this.account?.currency||"USD",duration:s.duration,duration_unit:s.durationUnit,barrier:s.barrier,symbol:s.market});const pid=proposal?.proposal?.id;if(!pid)throw new Error(proposal?.error?.message||"Proposal unavailable");this.pipelineStep="BUYING";const buy:any=await api_base.api.send({buy:pid,price:stake});const cid=String(buy?.buy?.contract_id||"");if(!cid)throw new Error(buy?.error?.message||"Buy failed");const oc:OpenContract={contractId:cid,signalId:s.id,market:s.market,marketName:s.marketName,contractType:s.contractType,contractLabel:s.contractLabel,barrier:s.barrier,durationTicks:s.duration,buyPrice:Number(buy.buy.buy_price??stake),potentialPayout:Number(buy.buy.payout??0),currentProfit:0,status:"open",buyTime:Date.now(),isSellable:true,mode:this.mode,accountLoginid:this.account!.loginid,baseSignalId:s.metadata?.baseSignalId||s.id,runIndex:s.metadata?.runIndex||1,runsTotal:s.metadata?.runsTotal||1,entryDigit:s.entryDigit,recoveryDigit:s.metadata?.recoveryDigit??null};this.open.set(cid,oc);this.session.tradesCount++;this.listenContract(cid,oc);executionJournal.logEvent({type:"BUY_CONFIRMED",signalId:s.id,message:"Contract purchased.",details:{contractId:cid,stake}});this.pipelineStep="IDLE";this.notify();return{ok:true,contractId:cid}}catch(e){this.latestError=e instanceof Error?e.message:String(e);this.pipelineStep="IDLE";this.notify();return{ok:false,error:this.latestError}}}
 private listenContract(cid:string,oc:OpenContract){if(!api_base.api)return;const sub:any=api_base.api.send({proposal_open_contract:1,contract_id:cid,subscribe:1});if(sub?.then)void sub.then((x:any)=>this.handleContract(x?.subscription?.data||x));const un=api_base.api.onMessage().subscribe((m:any)=>{const x=m?.data||m;if(x?.msg_type!=="proposal_open_contract"||String(x?.proposal_open_contract?.contract_id)!==cid)return;this.handleContract(x);if(x.proposal_open_contract?.is_sold||x.proposal_open_contract?.status==="sold")un.unsubscribe?.()})}
 private handleContract(m:any){const p=m?.proposal_open_contract;if(!p)return;const cid=String(p.contract_id);const oc=this.open.get(cid);if(!oc)return;oc.currentProfit=Number(p.profit??0);oc.currentSpot=Number(p.current_spot??p.current_spot_display??0)||oc.currentSpot;oc.entrySpot=Number(p.entry_spot??0)||oc.entrySpot;oc.exitSpot=Number(p.exit_spot??0)||oc.exitSpot;if(p.is_sold||p.status==="sold"){const pnl=Number(p.profit??0);oc.status=pnl>=0?"won":"lost";oc.settleTime=Date.now();this.session.netPnl+=pnl;this.session.accountPnl=Number((this.session.currentAccountBalance??this.baseline??0)-(this.baseline??this.session.startingBalance??0)+this.session.netPnl-(this.session.netPnl-pnl)).toFixed(2) as any;if(pnl>=0){this.session.wins++;this.session.consecutiveLosses=0;this.session.currentRecoveryStep=this.risk.resetAfterWin?0:this.session.currentRecoveryStep}else{this.session.losses++;this.session.consecutiveLosses++;if(this.risk.martingaleEnabled)this.session.currentRecoveryStep=Math.min(this.session.currentRecoveryStep+1,this.risk.maxRecoverySteps)}this.session.winRate=this.session.tradesCount?this.session.wins/this.session.tradesCount*100:0;executionJournal.updateTradeOutcome(cid,{result:pnl>=0?"WIN":"LOSS",pnl,settlementSpot:oc.exitSpot,durationMs:Date.now()-oc.buyTime});this.open.delete(cid);this.notify();this.continueRuns(oc,pnl)}}else{this.notify()}}
 private continueRuns(oc:OpenContract,pnl:number){const total=oc.runsTotal||1;const next=(oc.runIndex||1)+1;if(next>total)return;const base=this.queue.find(q=>q.signal.id===oc.baseSignalId)?.signal;if(!base)return;const nextSignal={...base,id:`${base.id}:run-${next}`,createdAt:Date.now(),expiresAt:Date.now()+Math.max(5000,this.risk.maxSignalAgeSeconds*1000),entryDigit:pnl<0?(oc.recoveryDigit??base.entryDigit):base.entryDigit,metadata:{...base.metadata,baseSignalId:oc.baseSignalId,runIndex:next,runsTotal:total,recoveryDigit:oc.recoveryDigit}};this.receiveSignal(nextSignal)}
 sellContract(id:string){if(!api_base.api)return Promise.resolve({ok:false,error:"No Deriv connection"});return api_base.api.send({sell:id,price:0}).then((r:any)=>r?.error?{ok:false,error:r.error.message}:{ok:true})}
 clearSignalQueue(){this.queue=[];this.staged=null;this.notify()}
}
export const sentinelExecutor=new SentinelForgeExecutor();
